# Generated by Django 6.0.2 on 2026-02-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point_off_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TO_COOK', 'To cook'), ('READY', 'Ready'), ('COMPLETED', 'Completed')], default='TO_COOK', max_length=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket', to='point_off_sale.order')),
            ],
        ),
    ]
