# Generated by Django 6.0.2 on 2026-02-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_display', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitchenTicket',
        ),
    ]
