# Generated by Django 6.0.2 on 2026-02-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_off_sale', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('to_cook', 'To Cook'), ('ready', 'Ready'), ('completed', 'Completed'), ('done', 'Done')], default='to_cook', max_length=20),
        ),
    ]
